config/routes.rb
Rails.application.routes.draw do
  root 'chat_rooms#index'
  resources :chat_rooms

  get '/join/:id' => 'chat_rooms#user_join', as: 'join_to_chat'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chat.rb
class Chat < ApplicationRecord
  belongs_to :user
  belongs_to :chat_room

  after_create :create_notify_pusher, on: :create
  def create_notify_pusher
    Pusher.trigger('chat', 'new', self.as_json)
  end
end

app/models/chat_room.rb
class ChatRoom < ApplicationRecord
  has_many :users_chat_rooms
  has_many :users, through: :users_chat_rooms
  has_many :chats

  after_commit :create_notify_pusher, on: :create
  after_commit :destroy_notify_pusher, on: :destroy
  after_commit :update_notify_pusher, on: :update

  def set_master_of_room(user)
    UsersChatRoom.create(user_id: user.id, chat_room_id: self.id)
  end

  def user_joined_room(user)
    UsersChatRoom.create(user_id: user.id, chat_room_id: self.id)
  end

  def create_notify_pusher
    Pusher.trigger('chat_room', 'create', self.as_json)
  end

  def destroy_notify_pusher
    Pusher.trigger('chat_room', 'destroy', self.as_json)
  end

  def update_notify_pusher
    Pusher.trigger('chat_room', 'update', self.as_json)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :users_chat_rooms
  has_many :chat_rooms, through: :users_chat_rooms
  has_many :chats
end

app/models/users_chat_room.rb
class UsersChatRoom < ApplicationRecord
  belongs_to :user
  belongs_to :chat_room
  after_commit :join_notify_pusher, on: :create
  # after_commit :exit_notify_pusher, on: :destroy

  def join_notify_pusher
    Pusher.trigger('join', 'create', self.user.email.as_json)
  end

  # def exit_notify_pusher
  #   Pusher.trigger('join', 'destroy', self.as_json)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/chat_rooms_controller.rb
class ChatRoomsController < ApplicationController
  before_action :set_chat_room, only: [:show, :edit, :update, :destroy, :user_join]
  before_action :authenticate_user!, except: [:index]

  # GET /chat_rooms
  # GET /chat_rooms.json
  def index
    @chat_rooms = ChatRoom.all
  end

  # GET /chat_rooms/1
  # GET /chat_rooms/1.json
  def show
    @chat = Chat.new
  end

  # GET /chat_rooms/new
  def new
    @chat_room = ChatRoom.new
  end

  # GET /chat_rooms/1/edit
  def edit
  end

  # POST /chat_rooms
  # POST /chat_rooms.json
  def create
    @chat_room = current_user.chat_rooms.new(chat_room_params)

    respond_to do |format|
      if @chat_room.save
        @chat_room.set_master_of_room(current_user)
        format.html { redirect_to @chat_room, notice: 'Chat room was successfully created.' }
        format.json { render :show, status: :created, location: @chat_room }
      else
        format.html { render :new }
        format.json { render json: @chat_room.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /chat_rooms/1
  # PATCH/PUT /chat_rooms/1.json
  def update
    respond_to do |format|
      if @chat_room.update(chat_room_params)
        format.html { redirect_to @chat_room, notice: 'Chat room was successfully updated.' }
        format.json { render :show, status: :ok, location: @chat_room }
      else
        format.html { render :edit }
        format.json { render json: @chat_room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /chat_rooms/1
  # DELETE /chat_rooms/1.json
  def destroy
    @chat_room.destroy
    respond_to do |format|
      format.html { redirect_to chat_rooms_url, notice: 'Chat room was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def user_join
    @chat_room.user_joined_room(current_user)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_chat_room
      @chat_room = ChatRoom.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def chat_room_params
      params.fetch(:chat_room, {}).permit(:title)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chat_rooms_helper.rb
module ChatRoomsHelper
end

app/views/chat_rooms/_form.html.erb
<%= form_for(chat_room) do |f| %>
  <% if chat_room.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(chat_room.errors.count, "error") %> prohibited this chat_room from being saved:</h2>

      <ul>
      <% chat_room.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/chat_rooms/edit.html.erb
<h1>Editing Chat Room</h1>

<%= render 'form', chat_room: @chat_room %>

<%= link_to 'Show', @chat_room %> |
<%= link_to 'Back', chat_rooms_path %>

app/views/chat_rooms/index.html.erb
<% if user_signed_in? %>
  <p><%= current_user.email %></p>
  <%= link_to 'logout', destroy_user_session_path, method: :delete %>
<% else %>
  <%= link_to 'login', new_user_session_path %>
<% end %>

<h1>Chat Rooms</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody id="chat-rooms">
    <% @chat_rooms.each do |chat_room| %>
      <tr class="room<%= chat_room.id %>">
        <td class="room_title<%= chat_room.id %>"><%= chat_room.title %></td>
        <td><%= link_to 'Show', chat_room %></td>
        <td><%= link_to 'Edit', edit_chat_room_path(chat_room) %></td>
        <td><%= link_to 'Destroy', chat_room, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Chat Room', new_chat_room_path %>

<script type="text/javascript">
$(document).on('ready', function() {
  function new_chat_room(data) {
    $('#chat-rooms').append(`
      <tr>
        <td>${data.title}</td>
        <td><a href="/chat_rooms/${data.id}">Show</a></td>
        <td><a href="/chat_rooms/${data.id}/edit">Edit</a></td>
        <td><a data-confirm="Are you sure?" rel="nofollow" data-method="delete" href="/chat_rooms/${data.id}">Destroy</a></td>
      </tr>`);
  }
  function destroy_chat_room(data) {
    $(`.room${data.id}`).remove();
  }
  function update_chat_room(data) {
    $(`.room_title${data.id}`).text(data.title);
  }
  var pusher = new Pusher('<%= ENV["pusher_key"] %>', {
    cluster: '<%= ENV["pusher_cluster"] %>',
    encrypted: true
  });
  var channel = pusher.subscribe('chat_room');
  channel.bind('create', function(data) {
    new_chat_room(data);
  });
  channel.bind('destroy', function(data) {
    destroy_chat_room(data);
  });
  channel.bind('update', function(data) {
    update_chat_room(data);
  })

})
</script>

app/views/chat_rooms/new.html.erb
<h1>New Chat Room</h1>

<%= render 'form', chat_room: @chat_room %>

<%= link_to 'Back', chat_rooms_path %>

app/views/chat_rooms/show.html.erb
<ul id="users-list">
<% @chat_room.users.each do |user| %>
  <li><%= user.email %></li>
<% end %>
</ul>
<hr>
<ul id="chats-list">
  <% @chat_room.chats.each do |chat| %>
    <%= chat.message %>
  <% end %>
</ul>
<%= form_tag('/chats') do %>
  <%= text_field_tag :message %>
<% end %>

<hr>
<% unless @chat_room.users.include?(current_user) %>
<%= link_to 'Join', join_to_chat_path(@chat_room), remote: true %> |
<% end %>
<%= link_to 'Edit', edit_chat_room_path(@chat_room) %> |
<%= link_to 'Back', chat_rooms_path %>

<script type="text/javascript">
$(document).on('ready', function() {
  function user_join(data) {
    $('#users-list').append(`<li>${data}</li>`)
  }
  var pusher = new Pusher('<%= ENV["pusher_key"] %>', {
    cluster: '<%= ENV["pusher_cluster"] %>',
    encrypted: true
  });
  var channel = pusher.subscribe('join');
  channel.bind('create', function(data) {
    user_join(data);
    console.log(data);
  });
})
</script>

app/views/chat_rooms/user_join.js.erb
alert('대화에 참가합니다!');

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ChatAppTest</title>
    <%= csrf_meta_tags %>
    <script src="https://js.pusher.com/4.1/pusher.min.js"></script>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>